services:
  obs_plate:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: obs-plate
    restart: unless-stopped
    ports:
      - "8789:80"
    volumes:
      - ./site:/usr/share/nginx/html:rw

  renderer:
    build:
      context: ./render
      dockerfile: Dockerfile
    container_name: overlay-renderer
    depends_on:
      - obs_plate
    volumes:
      - ./renders:/renders
    restart: "no"